language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && sudo apt-get update -qq && sudo apt-get install -qq gcc-4.9 g++-4.9 libgtk-3-dev pkg-config libgstreamer0.10-dev; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gtk+3 cairo; fi
  - mkdir build
  - cd build
  - cmake ..

script: make

os:
 - linux
 - osx

osx_image: xcode61
