language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository ppa:george-edison55/cmake-3.x -y && sudo apt-get update -qq && sudo apt-get install -qq cmake libgtk-3-dev pkg-config libgstreamer0.10-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install gtk+3 cairo; fi
  - mkdir build
  - cd build
  - cmake ..

script: make

os:
 - linux
 - osx

osx_image: xcode61
